theme: osuny
_merge: deep

params:
  plausible: a11yuniversites.org
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  logo:
    header: "/assets/images/logo-blanc.svg"
    footer: "/assets/images/logo.svg"
  persons:
    index:
      layout: grid
  posts:
    default_image: true
    index:
      options:
        author: true
        categories: true
        date: true
        image: true
        reading_time: true
        summary: true
        subtitle: true